### ISSUE TITLE
Defecto en el cron 

### ISSUE THREAD

**Issue by ghost** [Endika/digitalocean_integration#1]
![captura de pantalla de 2015-09-28 11 51 20](https://cloud.githubusercontent.com/assets/14206447/10141630/7270e48c-65d7-11e5-8939-4d41d6d0fca8.png)

aqui en esta linea:
![captura de pantalla de 2015-09-28 11 54 20](https://cloud.githubusercontent.com/assets/14206447/10141697/cab9e698-65d7-11e5-8663-9bd5ea254cc0.png)

**Comment by Endika** [comment]
Por lo que veo es que existe una máquina sin kernel definido? como es eso posible?

**Comment by ghost** [comment]
No creo que sea cosa de la api key , o si ?, tenemos que acomodar eso , antes que le suceda a otra persona 

----- Mensaje original -----

De: "Endika Iglesias" notifications@github.com 
Para: "Endika/digitalocean_integration" digitalocean_integration@noreply.github.com 
CC: "hroa" hroa@4geeks.com.ve 
Enviados: Lunes, 28 de Septiembre 2015 14:14:38 
Asunto: Re: [digitalocean_integration] Defecto en el cron (#1) 

Por lo que veo es que existe una máquina sin kernel definido? como es eso posible?

**Comment by ghost** [comment]
No se me ocurre nada para arreglarlo, Tu que harias ? 

----- Mensaje original -----

De: "Hendrix Roa" hroa@4geeks.com.ve 
Para: "Endika/digitalocean_integration" reply@reply.github.com 
Enviados: Lunes, 28 de Septiembre 2015 14:18:54 
Asunto: Re: [digitalocean_integration] Defecto en el cron (#1) 

No creo que sea cosa de la api key , o si ?, tenemos que acomodar eso , antes que le suceda a otra persona 

----- Mensaje original -----

De: "Endika Iglesias" notifications@github.com 
Para: "Endika/digitalocean_integration" digitalocean_integration@noreply.github.com 
CC: "hroa" hroa@4geeks.com.ve 
Enviados: Lunes, 28 de Septiembre 2015 14:14:38 
Asunto: Re: [digitalocean_integration] Defecto en el cron (#1) 

Por lo que veo es que existe una máquina sin kernel definido? como es eso posible?

**Comment by Endika** [comment]
He realizado pruebas de estrés al modulo y no he reproducido el error. Por otro lado el error que te da es de una linea que no existe. Esa linea no se encuentra en la posición ni tiene el contenido que indica el error que me muestras

**Comment by ghost** [comment]
Esa linea esta alli, lo que si cambie es que el cron que sincronza los droplets lo puse en minutos en vez de horas , eso repercute ? 

----- Mensaje original -----

De: "Endika Iglesias" notifications@github.com 
Para: "Endika/digitalocean_integration" digitalocean_integration@noreply.github.com 
CC: "hroa" hroa@4geeks.com.ve 
Enviados: Lunes, 28 de Septiembre 2015 15:25:58 
Asunto: Re: [digitalocean_integration] Defecto en el cron (#1) 

He realizado pruebas de estrés al modulo y no he reproducido el error. Por otro lado el error que te da es de una linea que no existe.

**Comment by Endika** [comment]
La linea de tu error es la 293
https://github.com/Endika/digitalocean_integration/blob/master/models/digital_droplet.py#L293
y esa linea no corresponde con `droplet.kernel['name'] if droplet.kernel['name'] is not None`
Por otro lado veo en tu log que te da un warning de la libreria urllib3 que la usa la propia api de digitalocean para comunicarse, no se si va por hay el error. No he sido capaz de reproducir el error. He sincronizado varias veces y no ha pasado nada.

**Comment by ghost** [comment]
exacto , pero total es un warning , no creo que cause problemas grandes, es para que cuando te pregunten sepas como contestarles, ya ese if se lo quite, y si creo que le quitare esa libreria tambien 

----- Mensaje original -----

De: "Endika Iglesias" notifications@github.com 
Para: "Endika/digitalocean_integration" digitalocean_integration@noreply.github.com 
CC: "hroa" hroa@4geeks.com.ve 
Enviados: Lunes, 28 de Septiembre 2015 15:57:03 
Asunto: Re: [digitalocean_integration] Defecto en el cron (#1) 

La linea de tu error es la 293 
https://github.com/Endika/digitalocean_integration/blob/master/models/digital_droplet.py#L293 
y esa linea no corresponde con droplet.kernel['name'] if droplet.kernel['name'] is not None 
Por otro lado veo en tu log que te da un warning de la libreria urllib3 que la usa la propia api de digitalocean para comunicarse, no se si va por hay el error. No he sido capaz de reproducir el error. He sincronizado varias veces y no ha pasado nada.

**Comment by Endika** [comment]
@hroa, lo siento mucho no reproduzco tu error, no se si has hecho modificaciones en el código pero la API y el modulo no fallan. Por lo tanto voy a cerrar el hilo. Muchas gracias por el aporte.

**Comment by ghost** [comment]
Si puedes borra toda la conversacion.
